### ISSUE TITLE
Users/  groups defined

### ISSUE THREAD

**Issue by minhson0506** [minhson0506/DatingApp-Hook#3]
Define the user type

**Comment by JulianCCY** [comment]
### Our target demographic:
- youngsters who are above the age of 18 due to age restriction (from survey)
- estimated age of the main users  is between 18 to 32 years old
- helping our users find true love (first priority), friendship, and hobby partner and bridging between the digital world and real world

**Comment by minhson0506** [comment]
Add activities, responsibilities, skill and goal ... for every user type
